### ISSUE TITLE
Unable to build the app with Sentry configured

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#250]
When env var `SENTRY_DSN` is defined the app fails to build.

**Comment by frodrigo** [comment]
Still the same issue when `SENTRY_DSN` is set in `.env`.

```
Step 13/18 : RUN yarn build
 ---> Running in 89c7758fd226
Nuxi 3.2.3
Nuxt 3.2.3 with Nitro 2.2.3

[@nuxtjs/i18n]  WARN  JS / TS extension format is experimental


[@nuxtjs/i18n]  WARN  i18n:extend-messages is deprecated. That hook will be removed feature at the time of the v8 official release.
If you're using it, please use i18n:registerModule instead.


 ERROR  Cannot read properties of undefined (reading 'options')

  at normalizedModule (node_modules/@nuxtjs/sentry/dist/module.mjs:59:12)
  at node_modules/@nuxtjs/sentry/dist/module.cjs:2:53
  at async installModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:435:15)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2256:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:2289:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2501:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:34:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

ERROR: Service 'vido' failed to build: The command '/bin/sh -c yarn build' returned a non-zero code: 1
```
